version: '3.7'

services:

  image:
    container_name: DataEng-Tp-Jenkins
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
